### ISSUE TITLE
Document that mobile services can't be installed on fedora 28

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#345]
## Description
SSIA, tried in virtual machine several instances, followed the docs, to no avail
## Suggested edit
a note in installation guide

@finp

**Comment by pmacko1** [comment]
@vchepeli could we get an opinion from qa pls?

**Comment by camilamacedo86** [comment]
It is not required because it will be fixed with the PR: https://github.com/aerogear/mobile-core/pull/193.
The problem here is to install in the versions 27 and 28.

**Comment by pmacko1** [comment]
@camilamacedo86 Hey, unfortunately the fix didn't work in fedora 28 in vm. I've updated https://github.com/aerogear/mobile-core/pull/193 Thanks

**Comment by camilamacedo86** [comment]
Hi Peter, 

Please don't forget that we checked that it will not work well on the well RHEL/CentOS 7.4 or RHEL/CentOS 7.5 because of an issue related to OCP. For further information see[1] 

Please, track an issue in the repo with all required information as description, and logs, and errors and all details/versions about your environment if you are not using RHEL/CentOS 7.4 or RHEL/CentOS 7.5. It is possible that you are facing some issue regards something specific in your environment. ( Execute the installer with the param --debug and add all output there )

[1] - https://github.com/aerogear/mobile-core/issues/194

**Comment by finp** [comment]
I know at one person was successfully running in fedora 28
