### ISSUE TITLE
Docs redirect could be improved

### ISSUE THREAD

**Issue by laurafitzgerald** [aerogear/mobile-docs#503]
## Description
Steps in the docs which are shown by clicking the link in the OpenShift console directs me to the main docs rather than any follow on steps.

## Expected Behavior
User gets relocated to the steps in the docs to follow after deploying the service

## Actual Behavior
User is relocated to the first step of the service docs.

## Environment

OSCP 3.11

## Steps to reproduce
Deploy Identity Management
Click the Documentation Link in the Application

@finp @pmacko1

**Comment by finp** [comment]
>Steps in the docs which are shown by clicking the link in the OpenShift console directs me to the main docs rather than any follow on steps.

Looks like the apb.yml for keycloak  links to https://docs.aerogear.org/external/apb/keycloak.html
and that redirects to 
https://docs.aerogear.org/aerogear/latest/identity-management.html

Isn't that what's expected? I tried the other links in the yml file and they all work fine. 

reference:
links are defined in https://github.com/aerogearcatalog/keycloak-apb/blob/master/apb.yml
redirects are defined in  https://github.com/aerogear/docs.aerogear.org/tree/master/external

**Comment by laurafitzgerald** [comment]
@finp yes the redirects work as they are written however (perhaps I worded the issue badly) but I think the logic should redirect the user to the steps in the doc which follow on from the provision. As the user is clicking the link from the provisioned service we can assume they've already done that step.

**Comment by finp** [comment]
@laurafitzgerald  maybe i read it wrong ;) your expected behaviour describes what you want perfectly (bad issue template?)
1. I'm assuming you'd want to update to https://docs.aerogear.org/aerogear/latest/identity-management.html#binding-a-mobile-client ?
2. This requires an update to https://docs.aerogear.org/external/apb/keycloak.html 
(you can do that directly, yourself?)

but even that is not perfect, I feel that jumping the user to that point is not correct. As you say 'somewhere after deploying' is what we want, and I think that the proper target is not obvious, and it might be good to revisit this as part of the productization effort.

**Comment by finp** [comment]
@laurafitzgerald  Is this still an issue?

**Comment by laurafitzgerald** [comment]
@finp let's close it. We recently did some work on linking the user to docs from MDC. This one is old now.
